// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8W_lid7T64SOqxljINqkVBIZ56FIBCaQ',
    appId: '1:761544089246:web:10c349d9d1359c76a5258f',
    messagingSenderId: '761544089246',
    projectId: 'herody-6473f',
    authDomain: 'herody-6473f.firebaseapp.com',
    storageBucket: 'herody-6473f.firebasestorage.app',
    measurementId: 'G-PXBKCJVGS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApjXHwRngYiwurPM-ZetOWzMV1ChrenyY',
    appId: '1:761544089246:android:aa0d2ccf70601cc7a5258f',
    messagingSenderId: '761544089246',
    projectId: 'herody-6473f',
    storageBucket: 'herody-6473f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtgz8t4aUfjDa_-h70AG8uLvc-k6Wcejg',
    appId: '1:761544089246:ios:a2a39c452dd1dee3a5258f',
    messagingSenderId: '761544089246',
    projectId: 'herody-6473f',
    storageBucket: 'herody-6473f.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtgz8t4aUfjDa_-h70AG8uLvc-k6Wcejg',
    appId: '1:761544089246:ios:a2a39c452dd1dee3a5258f',
    messagingSenderId: '761544089246',
    projectId: 'herody-6473f',
    storageBucket: 'herody-6473f.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8W_lid7T64SOqxljINqkVBIZ56FIBCaQ',
    appId: '1:761544089246:web:51dfca783cbbde85a5258f',
    messagingSenderId: '761544089246',
    projectId: 'herody-6473f',
    authDomain: 'herody-6473f.firebaseapp.com',
    storageBucket: 'herody-6473f.firebasestorage.app',
    measurementId: 'G-KV1WXSMW2H',
  );
}
